"""empty message

Revision ID: 5ccf72e73369
Revises: 58ca09ee68cf
Create Date: 2022-04-11 16:09:44.470419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccf72e73369'
down_revision = '58ca09ee68cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('appType', sa.String(length=100), nullable=True))
    op.drop_column('apps', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('apps', 'appType')
    # ### end Alembic commands ###
