"""empty message

Revision ID: b63599cbc2f7
Revises: 1bcb049e1a44
Create Date: 2022-04-14 12:39:42.876480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63599cbc2f7'
down_revision = '1bcb049e1a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'link')
    # ### end Alembic commands ###
